#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Apr 02, 2020 11:38:10 PM WAT  platform: Windows NT

import sys
import subprocess

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

i=0


def compiler(myres):
    global i

#    list=[r"C:\Users\User\Desktop\data.txt",r"C:\Users\User\Desktop\data1.txt"]
    print('unknown_support.compiler')
    
    
    sys.stdout.flush()
    fichier = open(r"C:\Users\ASUS\Desktop\compilation\test\a.txt", "r")
    i+=1
#   list_files = subprocess.run([r"C:\Users\User\Desktop\exemple.exe" "-o" "filename"   "filename.tab.c"    "lex.yy.c"] ,stdout=fichier,shell=True)
#    file = open(r"C:\Users\User\Desktop\data.txt", "r")

    lines = fichier.readlines()
    res=""
    for line in lines :
        
        res+=line+'\n'
    
    myres.set(res)
        
        




def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import unknown
    unknown.vp_start_gui()




